# Book settings
title: My Learning Blog
author: Your Name
logo: ""

# Execution settings
execute:
  execute_notebooks: auto

# Repository information
repository:
  url: https://github.com/st-1989/supreme-happiness
  path_to_book: ""
  branch: main

# HTML settings
html:
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: true

# Launch button settings
launch_buttons:
  notebook_interface: classic
  binderhub_url: ""
  colab_url: ""
